import { Montserrat, Poppins } from "next/font/google";
import "./globals.css";

  // const poppins = Poppins({
  //   variable: "--font-poppins",
  //   subsets: ["latin"],
  //   weights: ["400", "500", "600", "700", "800", "900"],
  // });

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weights: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Nirvoyo Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={` ${montserrat.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
